/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class RdsPPUiModule extends AbstractRdsPPUiModule {
}
