/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ui.tests;

import com.google.inject.Injector;
import de.rdspp.editor.ui.internal.EditorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RdsPPUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorActivator.getInstance().getInjector("de.rdspp.editor.RdsPP");
	}

}
