/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RdsPPProposalProvider extends AbstractRdsPPProposalProvider {
}
