/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.parser.antlr;

import com.google.inject.Inject;
import de.rdspp.editor.parser.antlr.internal.InternalRdsPPParser;
import de.rdspp.editor.services.RdsPPGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RdsPPParser extends AbstractAntlrParser {

	@Inject
	private RdsPPGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRdsPPParser createParser(XtextTokenStream stream) {
		return new InternalRdsPPParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RdsPPGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RdsPPGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
