/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RdsPPAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/rdspp/editor/parser/antlr/internal/InternalRdsPP.tokens");
	}
}
