/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ui;

import de.rdspp.editor.ui.AbstractRdsPPUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RdsPPUiModule extends AbstractRdsPPUiModule {
  public RdsPPUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
