/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP.impl;

import de.rdspp.editor.rdsPP.FunctionalAssignment;
import de.rdspp.editor.rdsPP.RdsPPPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Functional Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FunctionalAssignmentImpl extends RDSPPComponentImpl implements FunctionalAssignment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionalAssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdsPPPackage.Literals.FUNCTIONAL_ASSIGNMENT;
  }

} //FunctionalAssignmentImpl
