/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP.impl;

import de.rdspp.editor.rdsPP.InstallationLocationDescription;
import de.rdspp.editor.rdsPP.RdsPPPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Installation Location Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InstallationLocationDescriptionImpl extends RDSPPComponentImpl implements InstallationLocationDescription
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstallationLocationDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdsPPPackage.Literals.INSTALLATION_LOCATION_DESCRIPTION;
  }

} //InstallationLocationDescriptionImpl
