/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP.impl;

import de.rdspp.editor.rdsPP.LocationDescription;
import de.rdspp.editor.rdsPP.RdsPPPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Location Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LocationDescriptionImpl extends RDSPPComponentImpl implements LocationDescription
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocationDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdsPPPackage.Literals.LOCATION_DESCRIPTION;
  }

} //LocationDescriptionImpl
