/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP.impl;

import de.rdspp.editor.rdsPP.ProductDescription;
import de.rdspp.editor.rdsPP.RdsPPPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Product Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProductDescriptionImpl extends RDSPPComponentImpl implements ProductDescription
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProductDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdsPPPackage.Literals.PRODUCT_DESCRIPTION;
  }

} //ProductDescriptionImpl
