/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP.impl;

import de.rdspp.editor.rdsPP.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RdsPPFactoryImpl extends EFactoryImpl implements RdsPPFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static RdsPPFactory init()
  {
    try
    {
      RdsPPFactory theRdsPPFactory = (RdsPPFactory)EPackage.Registry.INSTANCE.getEFactory(RdsPPPackage.eNS_URI);
      if (theRdsPPFactory != null)
      {
        return theRdsPPFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new RdsPPFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RdsPPFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case RdsPPPackage.MODEL: return createModel();
      case RdsPPPackage.DECLARATION: return createDeclaration();
      case RdsPPPackage.RDSPP_MARKING: return createRDSPPMarking();
      case RdsPPPackage.RDSPP_COMPONENT: return createRDSPPComponent();
      case RdsPPPackage.SIGNAL_IDENTIFICATION: return createSignalIdentification();
      case RdsPPPackage.DOCUMENT_IDENTIFICATION: return createDocumentIdentification();
      case RdsPPPackage.FUNCTIONAL_ASSIGNMENT: return createFunctionalAssignment();
      case RdsPPPackage.FUNCTIONAL_DESIGNATION: return createFunctionalDesignation();
      case RdsPPPackage.INSTALLATION_LOCATION_DESCRIPTION: return createInstallationLocationDescription();
      case RdsPPPackage.LOCATION_DESCRIPTION: return createLocationDescription();
      case RdsPPPackage.CONNECTION_IDENTIFICATION: return createConnectionIdentification();
      case RdsPPPackage.COMMON_ASSIGNMENT: return createCommonAssignment();
      case RdsPPPackage.PRODUCT_DESCRIPTION: return createProductDescription();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Declaration createDeclaration()
  {
    DeclarationImpl declaration = new DeclarationImpl();
    return declaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RDSPPMarking createRDSPPMarking()
  {
    RDSPPMarkingImpl rdsppMarking = new RDSPPMarkingImpl();
    return rdsppMarking;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RDSPPComponent createRDSPPComponent()
  {
    RDSPPComponentImpl rdsppComponent = new RDSPPComponentImpl();
    return rdsppComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SignalIdentification createSignalIdentification()
  {
    SignalIdentificationImpl signalIdentification = new SignalIdentificationImpl();
    return signalIdentification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DocumentIdentification createDocumentIdentification()
  {
    DocumentIdentificationImpl documentIdentification = new DocumentIdentificationImpl();
    return documentIdentification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionalAssignment createFunctionalAssignment()
  {
    FunctionalAssignmentImpl functionalAssignment = new FunctionalAssignmentImpl();
    return functionalAssignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionalDesignation createFunctionalDesignation()
  {
    FunctionalDesignationImpl functionalDesignation = new FunctionalDesignationImpl();
    return functionalDesignation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InstallationLocationDescription createInstallationLocationDescription()
  {
    InstallationLocationDescriptionImpl installationLocationDescription = new InstallationLocationDescriptionImpl();
    return installationLocationDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LocationDescription createLocationDescription()
  {
    LocationDescriptionImpl locationDescription = new LocationDescriptionImpl();
    return locationDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConnectionIdentification createConnectionIdentification()
  {
    ConnectionIdentificationImpl connectionIdentification = new ConnectionIdentificationImpl();
    return connectionIdentification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CommonAssignment createCommonAssignment()
  {
    CommonAssignmentImpl commonAssignment = new CommonAssignmentImpl();
    return commonAssignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProductDescription createProductDescription()
  {
    ProductDescriptionImpl productDescription = new ProductDescriptionImpl();
    return productDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RdsPPPackage getRdsPPPackage()
  {
    return (RdsPPPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static RdsPPPackage getPackage()
  {
    return RdsPPPackage.eINSTANCE;
  }

} //RdsPPFactoryImpl
