/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP.impl;

import de.rdspp.editor.rdsPP.RdsPPPackage;
import de.rdspp.editor.rdsPP.SignalIdentification;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Signal Identification</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SignalIdentificationImpl extends RDSPPComponentImpl implements SignalIdentification
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SignalIdentificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdsPPPackage.Literals.SIGNAL_IDENTIFICATION;
  }

} //SignalIdentificationImpl
