/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ide

import com.google.inject.Guice
import de.rdspp.editor.RdsPPRuntimeModule
import de.rdspp.editor.RdsPPStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RdsPPIdeSetup extends RdsPPStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RdsPPRuntimeModule, new RdsPPIdeModule))
	}
	
}
