/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Common Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.rdspp.editor.rdsPP.RdsPPPackage#getCommonAssignment()
 * @model
 * @generated
 */
public interface CommonAssignment extends RDSPPComponent
{
} // CommonAssignment
