/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Functional Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.rdspp.editor.rdsPP.RdsPPPackage#getFunctionalAssignment()
 * @model
 * @generated
 */
public interface FunctionalAssignment extends RDSPPComponent
{
} // FunctionalAssignment
