/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Location Description</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.rdspp.editor.rdsPP.RdsPPPackage#getLocationDescription()
 * @model
 * @generated
 */
public interface LocationDescription extends RDSPPComponent
{
} // LocationDescription
