/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.rdspp.editor.rdsPP.RdsPPPackage
 * @generated
 */
public interface RdsPPFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RdsPPFactory eINSTANCE = de.rdspp.editor.rdsPP.impl.RdsPPFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration</em>'.
   * @generated
   */
  Declaration createDeclaration();

  /**
   * Returns a new object of class '<em>RDSPP Marking</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RDSPP Marking</em>'.
   * @generated
   */
  RDSPPMarking createRDSPPMarking();

  /**
   * Returns a new object of class '<em>RDSPP Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RDSPP Component</em>'.
   * @generated
   */
  RDSPPComponent createRDSPPComponent();

  /**
   * Returns a new object of class '<em>Signal Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Signal Identification</em>'.
   * @generated
   */
  SignalIdentification createSignalIdentification();

  /**
   * Returns a new object of class '<em>Document Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Document Identification</em>'.
   * @generated
   */
  DocumentIdentification createDocumentIdentification();

  /**
   * Returns a new object of class '<em>Functional Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Functional Assignment</em>'.
   * @generated
   */
  FunctionalAssignment createFunctionalAssignment();

  /**
   * Returns a new object of class '<em>Functional Designation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Functional Designation</em>'.
   * @generated
   */
  FunctionalDesignation createFunctionalDesignation();

  /**
   * Returns a new object of class '<em>Installation Location Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Installation Location Description</em>'.
   * @generated
   */
  InstallationLocationDescription createInstallationLocationDescription();

  /**
   * Returns a new object of class '<em>Location Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Location Description</em>'.
   * @generated
   */
  LocationDescription createLocationDescription();

  /**
   * Returns a new object of class '<em>Connection Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Connection Identification</em>'.
   * @generated
   */
  ConnectionIdentification createConnectionIdentification();

  /**
   * Returns a new object of class '<em>Common Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Common Assignment</em>'.
   * @generated
   */
  CommonAssignment createCommonAssignment();

  /**
   * Returns a new object of class '<em>Product Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Product Description</em>'.
   * @generated
   */
  ProductDescription createProductDescription();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RdsPPPackage getRdsPPPackage();

} //RdsPPFactory
