/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.rdsPP;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.rdspp.editor.rdsPP.RdsPPFactory
 * @model kind="package"
 * @generated
 */
public interface RdsPPPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rdsPP";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.rdspp.de/xtext/RdsPP";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rdsPP";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RdsPPPackage eINSTANCE = de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl.init();

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.ModelImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.DeclarationImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.RDSPPMarkingImpl <em>RDSPP Marking</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.RDSPPMarkingImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getRDSPPMarking()
   * @generated
   */
  int RDSPP_MARKING = 2;

  /**
   * The feature id for the '<em><b>Gemeinsame Zuordnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__GEMEINSAME_ZUORDNUNG = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Funktionsbezogene Kennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__FUNKTIONSBEZOGENE_KENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Funktionale Zuordnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__FUNKTIONALE_ZUORDNUNG = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Einbauortkennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__EINBAUORTKENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Aufstellungsortkennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__AUFSTELLUNGSORTKENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Produktbezogenekennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__PRODUKTBEZOGENEKENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Anschlusskennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__ANSCHLUSSKENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Signalkennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__SIGNALKENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Dokumentenkennzeichnung</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING__DOKUMENTENKENNZEICHNUNG = DECLARATION_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>RDSPP Marking</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_MARKING_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.RDSPPComponentImpl <em>RDSPP Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.RDSPPComponentImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getRDSPPComponent()
   * @generated
   */
  int RDSPP_COMPONENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_COMPONENT__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_COMPONENT__DESCRIPTION = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>RDSPP Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDSPP_COMPONENT_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.SignalIdentificationImpl <em>Signal Identification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.SignalIdentificationImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getSignalIdentification()
   * @generated
   */
  int SIGNAL_IDENTIFICATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_IDENTIFICATION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_IDENTIFICATION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Signal Identification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_IDENTIFICATION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.DocumentIdentificationImpl <em>Document Identification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.DocumentIdentificationImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getDocumentIdentification()
   * @generated
   */
  int DOCUMENT_IDENTIFICATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_IDENTIFICATION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_IDENTIFICATION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Document Identification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_IDENTIFICATION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.FunctionalAssignmentImpl <em>Functional Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.FunctionalAssignmentImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getFunctionalAssignment()
   * @generated
   */
  int FUNCTIONAL_ASSIGNMENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONAL_ASSIGNMENT__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONAL_ASSIGNMENT__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Functional Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONAL_ASSIGNMENT_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.FunctionalDesignationImpl <em>Functional Designation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.FunctionalDesignationImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getFunctionalDesignation()
   * @generated
   */
  int FUNCTIONAL_DESIGNATION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONAL_DESIGNATION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONAL_DESIGNATION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Functional Designation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONAL_DESIGNATION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.InstallationLocationDescriptionImpl <em>Installation Location Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.InstallationLocationDescriptionImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getInstallationLocationDescription()
   * @generated
   */
  int INSTALLATION_LOCATION_DESCRIPTION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_LOCATION_DESCRIPTION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_LOCATION_DESCRIPTION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Installation Location Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTALLATION_LOCATION_DESCRIPTION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.LocationDescriptionImpl <em>Location Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.LocationDescriptionImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getLocationDescription()
   * @generated
   */
  int LOCATION_DESCRIPTION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCATION_DESCRIPTION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCATION_DESCRIPTION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Location Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCATION_DESCRIPTION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.ConnectionIdentificationImpl <em>Connection Identification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.ConnectionIdentificationImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getConnectionIdentification()
   * @generated
   */
  int CONNECTION_IDENTIFICATION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_IDENTIFICATION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_IDENTIFICATION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Connection Identification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_IDENTIFICATION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.CommonAssignmentImpl <em>Common Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.CommonAssignmentImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getCommonAssignment()
   * @generated
   */
  int COMMON_ASSIGNMENT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_ASSIGNMENT__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_ASSIGNMENT__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Common Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_ASSIGNMENT_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.rdspp.editor.rdsPP.impl.ProductDescriptionImpl <em>Product Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.rdspp.editor.rdsPP.impl.ProductDescriptionImpl
   * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getProductDescription()
   * @generated
   */
  int PRODUCT_DESCRIPTION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_DESCRIPTION__NAME = RDSPP_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_DESCRIPTION__DESCRIPTION = RDSPP_COMPONENT__DESCRIPTION;

  /**
   * The number of structural features of the '<em>Product Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_DESCRIPTION_FEATURE_COUNT = RDSPP_COMPONENT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.rdspp.editor.rdsPP.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.rdspp.editor.rdsPP.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see de.rdspp.editor.rdsPP.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see de.rdspp.editor.rdsPP.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.RDSPPMarking <em>RDSPP Marking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RDSPP Marking</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking
   * @generated
   */
  EClass getRDSPPMarking();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getGemeinsameZuordnung <em>Gemeinsame Zuordnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Gemeinsame Zuordnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getGemeinsameZuordnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_GemeinsameZuordnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getFunktionsbezogeneKennzeichnung <em>Funktionsbezogene Kennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Funktionsbezogene Kennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getFunktionsbezogeneKennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_FunktionsbezogeneKennzeichnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getFunktionaleZuordnung <em>Funktionale Zuordnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Funktionale Zuordnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getFunktionaleZuordnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_FunktionaleZuordnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getEinbauortkennzeichnung <em>Einbauortkennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Einbauortkennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getEinbauortkennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_Einbauortkennzeichnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getAufstellungsortkennzeichnung <em>Aufstellungsortkennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Aufstellungsortkennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getAufstellungsortkennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_Aufstellungsortkennzeichnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getProduktbezogenekennzeichnung <em>Produktbezogenekennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Produktbezogenekennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getProduktbezogenekennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_Produktbezogenekennzeichnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getAnschlusskennzeichnung <em>Anschlusskennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Anschlusskennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getAnschlusskennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_Anschlusskennzeichnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getSignalkennzeichnung <em>Signalkennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Signalkennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getSignalkennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_Signalkennzeichnung();

  /**
   * Returns the meta object for the reference '{@link de.rdspp.editor.rdsPP.RDSPPMarking#getDokumentenkennzeichnung <em>Dokumentenkennzeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Dokumentenkennzeichnung</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPMarking#getDokumentenkennzeichnung()
   * @see #getRDSPPMarking()
   * @generated
   */
  EReference getRDSPPMarking_Dokumentenkennzeichnung();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.RDSPPComponent <em>RDSPP Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RDSPP Component</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPComponent
   * @generated
   */
  EClass getRDSPPComponent();

  /**
   * Returns the meta object for the attribute '{@link de.rdspp.editor.rdsPP.RDSPPComponent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPComponent#getName()
   * @see #getRDSPPComponent()
   * @generated
   */
  EAttribute getRDSPPComponent_Name();

  /**
   * Returns the meta object for the attribute '{@link de.rdspp.editor.rdsPP.RDSPPComponent#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see de.rdspp.editor.rdsPP.RDSPPComponent#getDescription()
   * @see #getRDSPPComponent()
   * @generated
   */
  EAttribute getRDSPPComponent_Description();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.SignalIdentification <em>Signal Identification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Signal Identification</em>'.
   * @see de.rdspp.editor.rdsPP.SignalIdentification
   * @generated
   */
  EClass getSignalIdentification();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.DocumentIdentification <em>Document Identification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Document Identification</em>'.
   * @see de.rdspp.editor.rdsPP.DocumentIdentification
   * @generated
   */
  EClass getDocumentIdentification();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.FunctionalAssignment <em>Functional Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Functional Assignment</em>'.
   * @see de.rdspp.editor.rdsPP.FunctionalAssignment
   * @generated
   */
  EClass getFunctionalAssignment();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.FunctionalDesignation <em>Functional Designation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Functional Designation</em>'.
   * @see de.rdspp.editor.rdsPP.FunctionalDesignation
   * @generated
   */
  EClass getFunctionalDesignation();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.InstallationLocationDescription <em>Installation Location Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Installation Location Description</em>'.
   * @see de.rdspp.editor.rdsPP.InstallationLocationDescription
   * @generated
   */
  EClass getInstallationLocationDescription();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.LocationDescription <em>Location Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Location Description</em>'.
   * @see de.rdspp.editor.rdsPP.LocationDescription
   * @generated
   */
  EClass getLocationDescription();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.ConnectionIdentification <em>Connection Identification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection Identification</em>'.
   * @see de.rdspp.editor.rdsPP.ConnectionIdentification
   * @generated
   */
  EClass getConnectionIdentification();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.CommonAssignment <em>Common Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Common Assignment</em>'.
   * @see de.rdspp.editor.rdsPP.CommonAssignment
   * @generated
   */
  EClass getCommonAssignment();

  /**
   * Returns the meta object for class '{@link de.rdspp.editor.rdsPP.ProductDescription <em>Product Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Description</em>'.
   * @see de.rdspp.editor.rdsPP.ProductDescription
   * @generated
   */
  EClass getProductDescription();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RdsPPFactory getRdsPPFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.ModelImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATIONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.DeclarationImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.RDSPPMarkingImpl <em>RDSPP Marking</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.RDSPPMarkingImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getRDSPPMarking()
     * @generated
     */
    EClass RDSPP_MARKING = eINSTANCE.getRDSPPMarking();

    /**
     * The meta object literal for the '<em><b>Gemeinsame Zuordnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__GEMEINSAME_ZUORDNUNG = eINSTANCE.getRDSPPMarking_GemeinsameZuordnung();

    /**
     * The meta object literal for the '<em><b>Funktionsbezogene Kennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__FUNKTIONSBEZOGENE_KENNZEICHNUNG = eINSTANCE.getRDSPPMarking_FunktionsbezogeneKennzeichnung();

    /**
     * The meta object literal for the '<em><b>Funktionale Zuordnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__FUNKTIONALE_ZUORDNUNG = eINSTANCE.getRDSPPMarking_FunktionaleZuordnung();

    /**
     * The meta object literal for the '<em><b>Einbauortkennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__EINBAUORTKENNZEICHNUNG = eINSTANCE.getRDSPPMarking_Einbauortkennzeichnung();

    /**
     * The meta object literal for the '<em><b>Aufstellungsortkennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__AUFSTELLUNGSORTKENNZEICHNUNG = eINSTANCE.getRDSPPMarking_Aufstellungsortkennzeichnung();

    /**
     * The meta object literal for the '<em><b>Produktbezogenekennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__PRODUKTBEZOGENEKENNZEICHNUNG = eINSTANCE.getRDSPPMarking_Produktbezogenekennzeichnung();

    /**
     * The meta object literal for the '<em><b>Anschlusskennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__ANSCHLUSSKENNZEICHNUNG = eINSTANCE.getRDSPPMarking_Anschlusskennzeichnung();

    /**
     * The meta object literal for the '<em><b>Signalkennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__SIGNALKENNZEICHNUNG = eINSTANCE.getRDSPPMarking_Signalkennzeichnung();

    /**
     * The meta object literal for the '<em><b>Dokumentenkennzeichnung</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RDSPP_MARKING__DOKUMENTENKENNZEICHNUNG = eINSTANCE.getRDSPPMarking_Dokumentenkennzeichnung();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.RDSPPComponentImpl <em>RDSPP Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.RDSPPComponentImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getRDSPPComponent()
     * @generated
     */
    EClass RDSPP_COMPONENT = eINSTANCE.getRDSPPComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RDSPP_COMPONENT__NAME = eINSTANCE.getRDSPPComponent_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RDSPP_COMPONENT__DESCRIPTION = eINSTANCE.getRDSPPComponent_Description();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.SignalIdentificationImpl <em>Signal Identification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.SignalIdentificationImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getSignalIdentification()
     * @generated
     */
    EClass SIGNAL_IDENTIFICATION = eINSTANCE.getSignalIdentification();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.DocumentIdentificationImpl <em>Document Identification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.DocumentIdentificationImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getDocumentIdentification()
     * @generated
     */
    EClass DOCUMENT_IDENTIFICATION = eINSTANCE.getDocumentIdentification();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.FunctionalAssignmentImpl <em>Functional Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.FunctionalAssignmentImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getFunctionalAssignment()
     * @generated
     */
    EClass FUNCTIONAL_ASSIGNMENT = eINSTANCE.getFunctionalAssignment();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.FunctionalDesignationImpl <em>Functional Designation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.FunctionalDesignationImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getFunctionalDesignation()
     * @generated
     */
    EClass FUNCTIONAL_DESIGNATION = eINSTANCE.getFunctionalDesignation();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.InstallationLocationDescriptionImpl <em>Installation Location Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.InstallationLocationDescriptionImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getInstallationLocationDescription()
     * @generated
     */
    EClass INSTALLATION_LOCATION_DESCRIPTION = eINSTANCE.getInstallationLocationDescription();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.LocationDescriptionImpl <em>Location Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.LocationDescriptionImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getLocationDescription()
     * @generated
     */
    EClass LOCATION_DESCRIPTION = eINSTANCE.getLocationDescription();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.ConnectionIdentificationImpl <em>Connection Identification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.ConnectionIdentificationImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getConnectionIdentification()
     * @generated
     */
    EClass CONNECTION_IDENTIFICATION = eINSTANCE.getConnectionIdentification();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.CommonAssignmentImpl <em>Common Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.CommonAssignmentImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getCommonAssignment()
     * @generated
     */
    EClass COMMON_ASSIGNMENT = eINSTANCE.getCommonAssignment();

    /**
     * The meta object literal for the '{@link de.rdspp.editor.rdsPP.impl.ProductDescriptionImpl <em>Product Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.rdspp.editor.rdsPP.impl.ProductDescriptionImpl
     * @see de.rdspp.editor.rdsPP.impl.RdsPPPackageImpl#getProductDescription()
     * @generated
     */
    EClass PRODUCT_DESCRIPTION = eINSTANCE.getProductDescription();

  }

} //RdsPPPackage
