/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRdsPPScopeProvider extends DelegatingScopeProvider {
}
