/*
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ui;

import com.google.inject.Injector;
import de.rdspp.editor.ui.internal.EditorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RdsPPExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EditorActivator.getInstance().getInjector(EditorActivator.DE_RDSPP_EDITOR_RDSPP);
	}
	
}
