/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ide;

import de.rdspp.editor.ide.AbstractRdsPPIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RdsPPIdeModule extends AbstractRdsPPIdeModule {
}
