/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.rdspp.editor.RdsPPRuntimeModule;
import de.rdspp.editor.RdsPPStandaloneSetup;
import de.rdspp.editor.ide.RdsPPIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RdsPPIdeSetup extends RdsPPStandaloneSetup {
  @Override
  public Injector createInjector() {
    RdsPPRuntimeModule _rdsPPRuntimeModule = new RdsPPRuntimeModule();
    RdsPPIdeModule _rdsPPIdeModule = new RdsPPIdeModule();
    return Guice.createInjector(Modules2.mixin(_rdsPPRuntimeModule, _rdsPPIdeModule));
  }
}
