/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor;

import de.rdspp.editor.RdsPPStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RdsPPStandaloneSetup extends RdsPPStandaloneSetupGenerated {
  public static void doSetup() {
    new RdsPPStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
