/**
 * generated by Xtext 2.12.0
 */
package de.rdspp.editor.ui.contentassist;

import de.rdspp.editor.ui.contentassist.AbstractRdsPPProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RdsPPProposalProvider extends AbstractRdsPPProposalProvider {
}
